package tr.com.kafein;// Generated by Selenium IDE

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;

public class SearchTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeEach
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void search() throws InterruptedException {
    // Test name: Search
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://www.google.com.tr/");
    // 2 | setWindowSize | 1040x800 | 
    driver.manage().window().setSize(new Dimension(1040, 800));
    // 3 | click | name=q | 
    driver.findElement(By.name("q")).click();
    // 4 | type | name=q | Kafein
    driver.findElement(By.name("q")).sendKeys("Kafein");
    // 5 | click | name=btnK | 

    driver.findElement(By.name("q")).submit();
    //driver.findElement(By.name("btnK")).click();

    Thread.sleep(10000);

  }
}
