package tr.com.kafein.hellogooglesearch;// Generated by Selenium IDE

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;

public class SearchGoogleTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeEach
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterEach
  public void tearDown() {

    driver.quit();
  }
  @Test
  public void searchGoogle() throws InterruptedException {
    // Test name: SearchGoogle
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://www.google.com.tr/");
    // 2 | setWindowSize | 1040x800 | 
    driver.manage().window().setSize(new Dimension(1040, 800));
    // 3 | click | name=q | 
    driver.findElement(By.name("q")).click();
    // 4 | type | name=q | Kafein
    driver.findElement(By.name("q")).sendKeys("Kafein");

    driver.findElement(By.name("q")).submit();
    // 5 | submit | name=q | 
    //throw new Error("`submit` is not a supported command in Selenium WebDriver. Please re-record the step in the IDE.");
    System.out.println(driver.getTitle());
    driver.navigate().back();
    System.out.println(driver.getCurrentUrl());
    driver.navigate().refresh();

    System.out.println(driver.getTitle());
    System.out.println(driver.getPageSource());
  }
}
