package tr.com.kafein.orderbasictests;// Generated by Selenium IDE

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.time.Duration;
import java.util.HashMap;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class BasicSportsStoreOrderTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeEach
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void basicSportsStoreOrder() {
    // Test name: BasicSportsStoreOrder
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://sportsstore.innovium.net/");
    // 2 | setWindowSize | max |
    driver.manage().window().maximize();
    // 3 | click | linkText=Home | 
    driver.findElement(By.linkText("Home")).click();
    // 4 | click | xpath=//button[@type='submit'] | 
    driver.findElement(By.xpath("//button[@type=\'submit\']")).click();
    // 5 | click | css=h2 | 
    driver.findElement(By.cssSelector("h2")).click();
    // 6 | waitForElementPresent | xpath=//h2[contains(.,'Your cart')] | 30000
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(5));
      wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//h2[contains(.,\'Your cart\')]")));
    }
    // 7 | click | linkText=Checkout | 
    driver.findElement(By.linkText("Checkout")).click();
    // 8 | click | css=h2 | 
    driver.findElement(By.cssSelector("h2")).click();
    // 9 | waitForElementVisible | xpath=//h2[contains(.,'Check out now')] | 30000
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(5));
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//h2[contains(.,\'Check out now\')]")));
    }
    // 10 | click | id=Name | 
    driver.findElement(By.id("Name")).click();
    // 11 | type | id=Name | John Doe
    driver.findElement(By.id("Name")).sendKeys("John Doe");
    // 12 | click | id=Line1 | 
    driver.findElement(By.name("Line1")).click();
    // 13 | type | id=Line1 | Silicon Hill Blv
    driver.findElement(By.name("Line1")).sendKeys("Silicon Hill Blv");
    // 14 | click | css=.form-group:nth-child(5) | 
    driver.findElement(By.cssSelector(".form-group:nth-child(5)")).click();
    // 15 | click | id=Line2 | 
    driver.findElement(By.id("Line2")).click();
    // 16 | type | id=Line2 | No 9
    driver.findElement(By.id("Line2")).sendKeys("No 9");
    // 17 | click | id=Line3 | 
    driver.findElement(By.xpath("//*[@id='Line3']")).click();
    // 18 | type | id=Line3 | 6785
    driver.findElement(By.id("Line3")).sendKeys("6785");
    // 19 | click | id=City |


    driver.findElement(By.id("City")).click();
    // 20 | type | id=City | Austin
    driver.findElement(By.id("City")).sendKeys("Austin");
    // 21 | click | id=State | 
    driver.findElement(By.id("State")).click();
    // 22 | type | id=State | TX
    driver.findElement(By.id("State")).sendKeys("TX");
    // 23 | click | id=Zip | 
    driver.findElement(By.id("Zip")).click();
    // 24 | type | id=Zip | 56422
    driver.findElement(By.id("Zip")).sendKeys("56422");
    // 25 | click | id=Country |

    driver.findElement(By.id("Country")).click();
    // 26 | type | id=Country | USA
    driver.findElement(By.id("Country")).sendKeys("USA");
    // 27 | click | css=.btn-primary | 
    driver.findElement(By.cssSelector(".btn-primary")).click();
    // 28 | click | css=h2 | 
    driver.findElement(By.cssSelector("h2")).click();
    // 29 | waitForElementVisible | css=h2 | 30000
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(5));
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector("h2")));
    }
    // 30 | click | css=p:nth-child(3) | 
    driver.findElement(By.cssSelector("p:nth-child(3)")).click();
    // 31 | assertText | css=p:nth-child(3) | We'll ship your goods as soon as possible.
    assertEquals(driver.findElement(By.cssSelector("p:nth-child(3)")).getText(), "We'll ship your goods as soon as possible.");
    // 32 | click | linkText=Return to Store | 
    driver.findElement(By.linkText("Return to Store")).click();
  }
}
